name: Absolute Force Deploy

on:
  push:
    branches: [main]
    paths:
      - 'prem_service/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'source'  # Явно указываем папку

      - name: Nuclear Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "1. Удаляем старые файлы..."
            rm -rf ~/prem-service/prem_service/*
            
            echo "2. Копируем новые файлы..."
            rsync -av $GITHUB_WORKSPACE/source/prem_service/ ~/prem-service/prem_service/
            
            echo "3. Проверяем результат:"
            ls -la ~/prem-service/prem_service
            
            echo "4. Перезапускаем сервис..."
            docker compose -f ~/prem-service/docker-compose.yml restart web
            echo "🔥 Всё перезаписано!"
