name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e  # Прерывать выполнение при ошибке
          set -x  # Выводить выполняемые команды
          
          # Переходим в рабочую директорию
          cd ./yanisgrek-main || { echo "Directory ./yanisgrek-main not found"; exit 1; }
          
          # Если папка code существует, но не является git репозиторием
          if [ -d "code" ] && [ ! -d "code/.git" ]; then
            echo "Directory 'code' exists but is not a git repo, removing..."
            rm -rf code
          fi
          
          # Если папки code нет или она пустая - клонируем заново
          if [ ! -d "code" ]; then
            echo "Cloning fresh repository..."
            git clone https://github.com/mrkiro52/yanisgrek.git code
            cd code
          else
            # Если репозиторий существует - обновляем
            cd code
            git fetch --all
            git reset --hard origin/main
            git clean -fd
          fi
          
          # Возвращаемся в корень и запускаем docker
          cd ..
          docker compose build app --no-cache
          docker compose up -d --no-deps app
          
          docker compose ps
          EOF
