name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e  # Прерывать выполнение при ошибке
          set -x  # Выводить выполняемые команды
          
          cd ./yanisgrek-main/code || { echo "Directory ./yanisgrek-main/code not found"; exit 1; }
          
          # Полная очистка и сброс репозитория
          git reset --hard HEAD
          git clean -fd
          git pull origin main --force
          
          # Возвращаемся в корень и запускаем docker
          cd ..
          docker compose build app --no-cache
          docker compose up -d --no-deps app
          
          docker compose ps
          EOF
