name: HARD Deploy prem_service

on:
  push:
    branches: [main]
    paths:
      - 'prem_service/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'prem_service'  # Ключевое изменение!

      - name: NUKE AND SYNC
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # 1. Удаляем ВСЁ в целевой папке (но не саму папку)
            rm -rf ~/prem-service/prem_service/*
            
            # 2. Копируем файлы из GitHub Actions
            scp -r $GITHUB_WORKSPACE/prem_service/* ~/prem-service/prem_service/
            
            # 3. Перезапуск
            cd ~/prem-service && docker compose restart web
            echo "☢️ Папка prem_service перезаписана!"
