name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ./yanisgrek-main
          
          # Полная очистка
          docker compose down -v
          docker builder prune -af
          docker system prune -af
          
          # Обновление кода
          git reset --hard
          git clean -fd
          git pull origin main
          
          # Пересборка с правильными правами
          docker compose build --no-cache
          docker compose run --rm app sh -c "\
            chown -R node:node /app && \
            npm install --unsafe-perm && \
            npm run build"
            
          docker compose up -d
          EOF
