name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e
          set -x
          
          # Основная рабочая директория
          WORK_DIR="./yanisgrek-main"
          cd $WORK_DIR || { echo "Directory $WORK_DIR not found"; exit 1; }
          
          # Если папка code не существует - создаем
          if [ ! -d "code" ]; then
            mkdir code
          fi
          
          # Очищаем папку code, кроме специальных файлов
          cd code
          find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          
          # Скачиваем и распаковываем только содержимое папки code из репозитория
          git archive --remote=https://github.com/mrkiro52/yanisgrek.git HEAD:code | tar -x
          
          # Возвращаемся и запускаем docker
          cd ..
          docker compose build app --no-cache
          docker compose up -d --no-deps app
          
          docker compose ps
          EOF
