name: HARD Deploy prem_service

on:
  push:
    branches: [main]
    paths:
      - 'prem_service/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Качаем код

      - name: NUKE AND SYNC
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # 1. Удаляем всю папку на сервере (если есть)
            rm -rf ~/prem-service/prem_service
            
            # 2. Копируем ВСЁ из репозитория
            cp -R /home/runner/work/repo/prem_service ~/prem-service/
            
            # 3. Перезапускаем сервис
            cd ~/prem-service && docker compose restart web
            echo "☢️ Папка prem_service полностью перезаписана!"
