name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ./yanisgrek-main
          
          # Обновляем только папку app
          git -C ./prila pull --force origin main
          
          # Пересобираем только сервис app
          docker compose build app --no-cache
          
          # Перезапускаем только app, nginx продолжает работать
          docker compose up -d --no-deps app
          
          # Проверяем статус
          docker compose ps
          EOF
