name: 100% Working Deploy

on:
  push:
    branches: [main]
    paths:
      - 'prem_service/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Nuclear Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # 1. Создаем архив прямо в репозитории
            tar -czf /tmp/repo.tar.gz -C prem_service .
            
            # 2. Копируем архив на сервер
            scp /tmp/repo.tar.gz ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/tmp/
            
            # 3. Распаковываем и перезапускаем
            ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "
              echo 'Удаляем старую папку...'
              rm -rf ~/prem-service/prem_service/*
              
              echo 'Распаковываем архив...'
              tar -xzf /tmp/repo.tar.gz -C ~/prem-service/prem_service
              
              echo 'Содержимое после деплоя:'
              ls -la ~/prem-service/prem_service
              
              echo 'Перезапуск контейнера...'
              cd ~/prem-service && docker compose restart web
              
              echo 'Статус контейнера:'
              docker ps | grep web
            "
            echo '✅ Всё обновлено и перезапущено!'
